version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DETAILED_ERRORS=true
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=tvshop;User=root;Password=mysqlpass123;AllowPublicKeyRetrieval=true;Convert Zero Datetime=True;ConnectionTimeout=300;DefaultCommandTimeout=300;
    volumes:
      - data-protection:/home/appuser/.aspnet/DataProtection-Keys
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tvshop-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass123
      - MYSQL_DATABASE=tvshop
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - tvshop-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
  data-protection:

networks:
  tvshop-network:
    driver: bridge
